---
Description: Storage bucket for AWS Config Lambda code.
Parameters:
  LambdaBucketName:
    Description: Name for the S3 bucket for Lambda code used in AWS Config
    Type: String
Resources:
  BackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        !Ref LambdaBucketName
  BackupBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        !Ref BackupBucket
      PolicyDocument:
        Version: "2012-10-17"
        Id: PutObjPolicy
        Statement:
          -
            Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Action:
              - s3:PutObject
            Principal: "*"
            Resource: !Sub |
              arn:aws:s3:::${LambdaBucketName}/*
            Condition:
              StringNotEquals:
                "s3:x-amz-server-side-encryption": "aws:kms"